import React from "react";
import Layout from "./../Components/Layout/Layout";
import TermsCondMenu from "./TermsCondMenu";
import "./termsCond.css";

function TermsAndConditions() {
  return (
    <Layout>
      <div className="container">
        <div className="row ">
          {/* <div className="col-md-5 position-fixed top-0 start-0 z-3"> */}
          <div className="col-md-4 termsCol1 ">
            <TermsCondMenu className="" />
          </div>
          <div className="col-md-8">
            <h3 className=" py-lg-3 py-xl-3 py-md-2 py-2 termHead my-2 my-xl-4 my-lg-4 my-md-3 my-sm-3 ">
              Terms and Conditions
            </h3>
            <p className="termsP">
              General Reliance Retail Limited, having its registered office at
              3rd Floor, Court House, Lokmanya Tilak Marg, Dhobi Talao,
              Mumbai–400002, Maharashtra, India (collectively referred to as
              “Reliance”, “we”, “us” or “our”) is managing and operating the
              website www.tannisbeauty.com, and its corresponding mobile/tablet
              applications (collectively referred to as “Tannis”, or “website”,
              or “app”), which inter alia facilitates the sale and purchase of
              various beauty and personal care products (“Products”) to the
              customer (collectively referred to as “Customer” or “user” or
              “users” or “you” or “your”).
              <br />
              The user may browse through the Products listed for sale on the
              website and avail services related to such Products (“Services”).
              You may also be using our interactive services (“Interactive
              Services”) such as our beauty assistance, which will be subject to
              these Terms.
              <br />
              Only persons who can enter into legally binding contracts as per
              the Indian Contract Act, 1872, i.e., persons who are 18 years of
              age or older, are of sound mind, and are not disqualified from
              entering into contracts by any law, can use and access Tannis. If
              you are a minor i.e., under the age of 18 years, you may use
              Tannis only with the involvement of a parent or guardian.
              <br />
              By using the website, you expressly agree that these Terms and
              Conditions (“Terms” or “Terms and Conditions”) govern your usage,
              of the website, sale and purchase of the Products on the website,
              access to Services, rights and obligations arising by virtue of
              usage of any feature of the website. These Terms and Conditions
              form a binding Agreement between Reliance and the Customer
              (“Agreement”) within the scope of Section 10A of the Information
              Technology Act, 2000 read with the Indian Contract Act, 1872.
              Please note that your usage of the website, the Products, offers
              or promotions in relation to the Products and the Services as may
              be provided by us or our affiliates or third parties, shall be
              governed by these Terms and such other terms that may be
              applicable (“Additional Terms”). If these Terms are inconsistent
              with such Additional Terms, the Additional Terms will control to
              the extent of such inconsistency with respect to the applicable
              Service or the Product. If you do not agree with any of the Terms,
              we advise you not to use or access the website.
              <br />
              These Terms and Conditions constitute an electronic record within
              the meaning of the applicable law. This electronic record is
              generated by a computer system and does not require any physical
              or digital signatures. The Terms and Conditions consist of
              following sections i.e. (i) ‘Terms of Use of Tannis’; (ii) ‘Terms
              of Sale’; and (iii) ‘Miscellaneous’; respectively. Please read
              these Terms and Conditions carefully before using or accessing
              Tannis. By using Tannis or availing of any Service, you signify
              your agreement to be bound by these Terms and Conditions.
            </p>
            <h2 className="termsh1 mb-2">Part A – Terms of Use of Tannis</h2>
            <h2 className="termsh1 mb-2">
              {" "}
              1. Registration and Operation of Your Account
            </h2>
            <p className="termsP mb-2">
              1.1. In order to use Tannis, you will have to register on the
              website. Registration is a one-time process and is free of cost.
              You can register on Tannis via below mentioned process:
            </p>
            a) <h2 className="termsh1 m">By using your mobile number.</h2>
            <span className="termsP">
              You can register by providing relevant information, such as your
              mobile number, name, gender, and other details relevant to
              creating an account. Your login ID and password will be created
              basis the information provided by you, which you can use to access
              your Tannis account at any time.
            </span>
            b) <h2 className="termsh1">By using social media login. </h2>
            <span className="termsP">
              {" "}
              By using a third party account you may use the login credentials
              from a third party account as identified by Reliance (e.g. Google
              or Facebook). If you use such third party accounts you will also
              be subject to such third party terms and conditions applicable to
              third party accounts as may be imposed by the relevant third party
              from time to time. It may be noted that any fraudulent activity or
              abuse of your Tannis account due to login via social media is not
              attributable to Reliance.
            </span>
            <p className="termsP my-2">
              1.2. Due to inactivity in your Account for a substantial time, you
              may get automatically logged out of your account or you may choose
              to log out of your account. In case you are logged out of your
              account and wish to log in, you may log in via One Time Password
              verification via your registered mobile number.
            </p>
            <p className="termsP">
              {" "}
              1.3. Your credentials shared by you at the time of registration
              and your Tannis login ID and password are referred to as “Account
              Information”.
            </p>
            <p className="termsP">
              1.4. You are solely authorised to operate the account created by
              you. Consequently, it is your responsibility to maintain the
              confidentiality of the Account Information and for restricting
              access to your computer/mobile/other similar devices to prevent
              unauthorised access to your account. You will at all times keep
              your Account Information up-to-date and accurate. You can access
              and update the Account Information under the ‘My Profile’ section
              of the website.
            </p>
            <p className="termsP">
              1.5. You also have the option to browse through the Tannis Content
              and make purchases as a ‘Guest’. If you choose to proceed as a
              ‘Guest’, the details of the orders placed by you on the website
              will not be available for you to review. You will however receive
              the necessary communication and updates regarding your orders.
              Should you require any assistance or information pertaining to
              such orders placed by you, you may contact customer support.
            </p>
            <p className="termsP">
              1.6. You will: (a) immediately inform Reliance of any unauthorised
              usage of the account or any other security breach; and (b) ensure
              that you log out of your account at the end of each session.
              Reliance will not be liable for any loss or direct or indirect
              damage arising from your failure to comply with these Terms and
              Conditions. You may be held liable for any losses incurred to
              Reliance or any other user due to unauthorised use of their
              account, resulting from your failure to keep your Account
              Information safe, secure and confidential. We reserve the right to
              refuse access to Tannis, terminate accounts, or remove or edit
              content at any time without notice to you.
            </p>
            <h2 className="temsh1">2. Communication and Unsubscription</h2>
            <p className="termsP">
              2.1. You understand that once you have shared your Account
              Information and successfully registered on Tannis, you may receive
              SMS or email notifications from Reliance relating to your
              registration and transactions on Tannis.{" "}
            </p>
            <p className="termsP">
              2.2. You may also receive such notifications regarding any
              marketing / promotional activities that may be available on Tannis
              from time to time. By sharing your Account Information and
              registering on Tannis and/ or verifying your contact number with
              us, you explicitly consent to receive marketing/ promotional
              communications (through call, SMS, email or other digital and
              electronic means) from us and/or our authorised representatives
              regarding any new services or offerings, even if your contact
              number is registered under the DND/NCPR list under the Telecom
              Commercial Communications Customer Preference Regulations, 2018.{" "}
            </p>
            <p className="termsP">
              2.3. Reliance may also send notifications and reminders with
              respect to the Services on Tannis. While Reliance endeavours to
              provide these notifications and reminders to you promptly,
              Reliance does not provide any guarantee and will not be held
              liable or responsible for any failure to send such
              notifications/reminders to you.{" "}
            </p>
            <p className="termsP">
              2.4. You can unsubscribe / opt-out from receiving marketing/
              promotional communications, newsletters and other notifications
              from Reliance at any time by following the instructions set out in
              such communications.{" "}
            </p>
            <p className="termsP">
              2.5. Please note all calls made by/to us are confidential in
              nature. However, the users’ calls may be recorded and monitored to
              ensure the quality of service and for training purposes.{" "}
            </p>
            <h2 className="termsh1">3. Access to Images</h2>
            3.1. By accepting the Terms and Conditions, you provide explicit
            consent to access your camera and gallery applications installed in
            your phone or computer, through which you operate Tannis.
            <p className="termsP">
              3.2. Tannis also gives its users an option to upload an image as
              their profile picture on the website for a customised and
              exclusive experience. You acknowledge and agree that in addition
              to the restrictions set out in paragraph 8 (User Warranties and
              Restrictions), you will ensure that any image uploaded by you: (i)
              does not belong to another person, in relation to which you do not
              have any right; or (ii) such image is not defamatory, obscene,
              pornographic, paedophilic, invasive of another’s privacy,
              including bodily privacy, insulting or harassing on the basis of
              gender, libellous, racially or ethically objectionable; or (iii)
              is not harmful to child; (iv) should not infringe any copyright or
              other proprietary rights; (v) does not impersonate another person;
              or (vi) does not contain software virus or any other computer
              code, file or program designed to interrupt, destroy or limit the
              functionality of any computer resource; or (vii) should not
              contain indecent representation of women in any form; or (viii)
              violates any law for the time being in force, including but not
              limited to Information Technology Act, 2000, Indecent
              Representation of Women (Prohibition) Act, 1986 and Indian Penal
              Code 1860, and the rules made thereunder (as applicable).
            </p>
            <p className="termsP">
              3.3. Should the images uploaded by you be covered by intellectual
              property rights, belonging to you or assigned to you by a
              third-party, you hereby grant Tannis a non-exclusive,
              royalty-free, transferable, sub-licensable, worldwide license to
              use, distribute, copy, or display, translate and create derivative
              works of the images that you upload, solely in connection with
              Products and Services available on Tannis.
            </p>
            <p className="termsP">
              3.4. In the event of a breach of any of the obligations mentioned
              in this paragraph 3 (Access to Images), you accept that we will
              not be liable to you or any third-party in relation to any claims,
              losses, liabilities, damages, and/or costs (including any attorney
              fees and costs) which may arise from a breach of the aforesaid
              obligations. You further agree that you will be liable to
              indemnify us in accordance with paragraph 9 (Indemnification and
              Limitation of Liability) of the Terms.{" "}
            </p>
            <h2 className="termsh1">4. License and Access to The Platform</h2>
            <p className="termsP">
              4.1. Your use of the website and access to Tannis Content (as
              defined below) is subject to a limited, revocable and
              non-exclusive license which is granted to you when you register on
              the website. You will use Tannis solely for the intended purpose.{" "}
            </p>
            <p className="termsP">
              4.2. The license granted to you does not include a license for (a)
              the resale of Products or commercial use of Tannis or Tannis
              Content, (b) any collection and use of Product listings,
              description, or prices, (c) any use of Tannis, other than as
              contemplated in these Terms and Conditions, (d) any downloading or
              copying of Account Information, (e) any use of data mining,
              robots, or similar data gathering and extraction tools to extract
              (whether once or many times) any parts of Tannis, (f) creating
              and/ or publishing your own database that features parts of
              Tannis.{" "}
            </p>
            <p className="termsP">
              4.3. You grant to Reliance a royalty-free, perpetual, irrevocable,
              non-exclusive right and license to adopt, publish, reproduce,
              disseminate, transmit, distribute, copy, use, create derivative
              works from, display worldwide, or act on any material posted by
              you on the website, including comments, or posts on social media
              without additional approval or consideration in any form, media,
              or technology now known or later developed, for the full term of
              any rights that may exist in such content, and you waive any claim
              over all feedback, comments, ideas or suggestions or any other
              content provided through or on Tannis. You agree to perform all
              further acts necessary to perfect any of the above rights granted
              by you to Reliance, including the execution of deeds and
              documents, at its request.{" "}
            </p>
            <p className="termsP">
              4.4. Please note that Reliance at all times reserves the right to
              refuse your access to the website, terminate your license to use
              the website, terminate/deactivate your account, remove or edit
              content on Tannis, at its sole discretion, without any prior
              notice.{" "}
            </p>
            <h2 className="termsh1"> 5. Personal Information Privacy </h2>
            <p className="termsP">
              5.1. During the course of your registration on and usage of
              Tannis, Reliance may collect and store and/or you may provide us
              with, personal identifiable and sensitive information about you,
              including without limitation your name, phone number, email
              address, address, postal code, occupation, login details etc.
            </p>
            <p className="termsP">
              5.2. Reliance respects the sensitivity of the information about
              you and we appreciate your trust in us. In this regard, Reliance
              has formulated the Privacy policy, which shall be deemed to be
              included in these Terms and Conditions, setting out the manner in
              which your information is collected, stored, processed, used and
              disclosed. If you do not agree with the terms of our Privacy
              policy, we advise you to not use or access Tannis.
            </p>
            <h2 className="termsh1">6. Content on Tannis </h2>
            <p className="termsP">
              6.1. All information, content, material, text, graphics, images,
              logos, button icons, software code, interface, design and the
              collection, arrangement and assembly of the content on Tannis or
              any of the other services are the property of Reliance or its
              affiliates (“Tannis Content”), and are protected under copyright,
              trademark and other applicable laws. Further, all trademarks,
              service marks, trade names and trade secrets in relation to Tannis
              whether or not displayed on Tannis, are proprietary to Reliance.
            </p>
            <p className="termsP">
              6.2. Reliance may display on Tannis any third-party logos, trade
              names, or trademarks of other brands, as per the license granted
              to Reliance by such brands.
            </p>
            <p className="termsP">
              6.3. No information, content or material from Tannis (including
              the Tannis Content) may be copied, reproduced, republished,
              duplicated, copied, sold, resold, uploaded, posted, transmitted,
              distributed or otherwise exploited in any way (including for any
              commercial purpose) without Reliance’s express written permission.
              You will not frame or use framing techniques to enclose any
              trademark, logo, or other proprietary information (including
              images, text, page layout, or form) of Reliance and its affiliates
              without express written consent. You may not use any meta tags or
              any other “hidden text” utilizing Reliance’s or its affiliates’
              names or trademarks without the express written consent of
              Reliance and/or its affiliates, as applicable. Any unauthorised
              use terminates the permissions granted in these Terms and
              Conditions.
            </p>
            <h2 className="termsh1"> 7. Disclaimers </h2>
            <p className="termsP">
              7.1. Reliance will try to make access to and use of Tannis
              error-free and without interruptions. However, your access to
              Tannis may be occasionally suspended or restricted to allow for
              repairs, maintenance, or for the introduction of new facilities or
              services on Tannis. Reliance does not take responsibility for any
              access or usage problems that may arise from internet related
              issues at your end.
            </p>
            <p className="termsP">
              7.2. Tannis may contain user generated content which Reliance does
              not pre-screen and which contains views that may be opinions of
              users/ experts. Reliance will do its best to monitor, edit or
              remove such user-generated content where it is necessary to do so
              (for instance, if such content violates these Terms and
              Conditions). Reliance does not promise that the user generated
              content on Tannis is accurate, complete or updated, that it will
              not offend or upset any person or that it does not infringe the
              intellectual property rights of third parties.
            </p>
            <p className="termsP">
              7.3. To help you in identifying the Products of your choice,
              descriptions of the Products are provided on Tannis through
              photographs, videos, charts, screenshots, infographics and other
              visual aids. While reasonable efforts are made to provide accurate
              visual representations, we disclaim any guarantee or warranty of
              exactness of such visual representation or description of the
              Products, with the actual Product which is ultimately delivered to
              you. The appearance/colour of the Products when delivered may
              differ for various reasons.
            </p>
            <p className="termsP">
              7.4. The Products and/or Services purchased/ received/ availed on
              the website may cause side effects or may not suit you. Please
              note that Reliance is in no manner responsible for any
              manufacturing or Product side-effects. Service provider and
              manufacturer or service provider of the relevant Product or
              service shall be solely responsible for such side effects and
              consumer complaints. We advise you to carefully read the
              individual terms and conditions in relation to the Products and
              consult a specialist before the use of the same.
            </p>
            <p className="termsP">
              7.5. The Products and/or Services included on Tannis are provided
              on an “as is” and “as available” basis without any representations
              or warranties, express or implied, except as otherwise specified
              in writing. Reliance does not covenant or provide any
              representations and warranties:
            </p>
            <p className="termsP">
              a) in respect of quality, suitability, accuracy, reliability,
              performance, safety, merchantability, fitness for a particular
              purpose/consumption or the content (including Product or pricing
              information and/or specifications) on Tannis;
            </p>
            <p className="termsP">
              b) that the Products or Services will be made available at all
              times;
            </p>
            <p className="termsP">
              c) that the operation of Tannis, including the functions contained
              in any content, information and materials on Tannis or any
              third-party sites or services linked to Tannis will be
              uninterrupted, or that the defects will be rectified, or that
              Tannis or the servers that make such content, information and
              materials available are free of viruses or other harmful
              components; and
            </p>
            <p className="termsP">
              d) that Tannis Content available on the website is complete, true,
              accurate or not misleading.
            </p>
            <p className="termsP">
              7.6. Parties other than Reliance and its affiliates may operate
              stores, provide services on Tannis. We are not responsible for
              examining or evaluating, and we do not warrant or endorse the
              offerings of any of these businesses or individuals, or the
              content made available by them. Reliance does not assume any
              responsibility or liability for the actions, Products, and content
              of any of these and any other third parties. The information
              displayed or any recommendation made to you on the website during
              the course of your use of the website is purely for informational
              purposes and for your convenience and does not amount to or be
              deemed to be an endorsement of any Product or service under any
              circumstances.
            </p>
            <p className="termsP">
              7.7. You understand that the website may provide third-party
              services to help you locate and purchase Products. Please note
              that this service is provided by third-party, and the website does
              not guarantee nor make any representation with respect to the
              correctness, completeness or accuracy of such services. You should
              seek emergency help or follow-up care when required and continue
              to consult your primary health advisor as you may deem fit.
            </p>
            <p className="termsP">
              7.8. Any liability or claim arising out of such third-party
              services availed by you shall be between you and such third-party.
              The company disclaims any liability that may arise out of your
              communication, availment of services (including but not limited to
              deficiency, shortcoming, and inaccuracy) with such third parties.
            </p>
            <p className="termsP">
              7.9. To the extent permitted by applicable law, Reliance disclaims
              any liability against any loss, damage, expenses, liabilities,
              claim, injury caused due to the failure of performance, omission,
              defect of Products, or deletion, interruption, error, delay,
              virus, communication, unauthorised access, theft, destruction,
              alteration or use of records on Tannis.
            </p>
            <p className="termsP">
              7.10. Reliance is not responsible for the content of any
              third-party sites and does not make any representations regarding
              the content or accuracy of material on such sites. If you decide
              to access links of any third-party platforms, you are doing so
              entirely at your own risk and expense.
            </p>
            <p className="termsP">
              7.11. The Interactive Services provided on the website is to help
              you with select Products and Services related queries. Any use of
              this functionality shall be subject to the following conditions:
            </p>
            <p className="termsP">
              a) Reliance, employees, directors or its affiliates are not
              responsible for any suggestions/recommendations made by the beauty
              advisors from time to time. It is hereby clarified that all
              recommendations are provided only basis the information you
              provide to us during the Interactive Services. It is always
              recommended before using any new Product, please remember to read
              and follow the appropriate directions for use. If you have a
              specific skin condition, allergy, or sensitivity, it is advisable
              to always consult your doctor/perform a patch test as you deem
              fit, before introducing any Product to your skincare regimen. The
              Products suggested are purely on the basis of the
              description/details shared by you above.
            </p>
            <p className="termsP">
              b) Reliance or its affiliates are not responsible for any delay
              caused in attending to or replying to the queries via chat.
            </p>
            <p className="termsP">
              c) Communication through chat may be stored by Reliance for future
              reference, to improve the quality of service or resolve your
              concern, and the user of such service will not have the right to
              access such information at any future date.
            </p>
            <p className="termsP">
              d) While using this feature you may not communicate any
              objectionable information i.e. unlawful, threatening, abusive,
              defamatory, obscene information.
            </p>
            <p className="termsP">
              e) This feature shall not be used to sell any Products, to give
              suggestion on business opportunity or any other form of
              solicitation.
            </p>
            <p className="termsP"></p>f) You may proceed further and consult
            with our online Customer care executive and avail the beauty service
            only if you agree to the above conditions.
            <p className="termsP">
              7.12. Reliance does not warrant that Tannis will be compatible
              with all hardware and software which is used by the user.
            </p>
            <p className="termsP">
              7.13. While we attempt to provide you error free and smooth
              experience, in case of an inadvertent error there may be
              information on Tannis that contains typographical errors,
              inaccuracies or omissions that may relate to information
              pertaining to the Products, pricing, promotions, offers, shipping
              charges, transit times and availability. Reliance reserves the
              right to correct any errors, inaccuracies or omissions, and to
              change or update information if any information on the website is
              inaccurate at any time without prior notice.
            </p>
            <p className="termsP">
              7.14. The offers, discounts and other promotional offers displayed
              may vary for the users based on factors relating to the user such
              as usage of the website, volume of transactions, time spent on the
              website, city, place of residence, time, etc.
            </p>
            <h2 className="termsh1"> 8. User Warranties and Restrictions </h2>
            <p className="termsP">
              8.1. You represent and warrant that: (a) your use of Tannis will
              not violate any applicable law or regulation; (b) all information
              that is submitted to Reliance in connection with Tannis is true,
              accurate and lawful; (c) use of the content and material you
              supply does not breach any applicable Tannis policies or
              guidelines and will not cause injury to any person or entity
              (including that the content or material is not defamatory). If at
              any time, the information provided by you is found to be false or
              inaccurate, Reliance will have the right to reject registration,
              cancel all orders, and restrict you from using the Services and
              other affiliated services in the future without any prior
              intimation whatsoever. You agree to indemnify Reliance and its
              affiliates for all claims brought by a third-party against it or
              its affiliates arising out of or in connection with a breach of
              any of these warranties.
            </p>
            <p className="termsP">
              8.2. The Products and Services available on the website, and the
              samples, if any, that website may provide you, are for your
              personal use only. The Products or Services, or samples thereof,
              which you may receive from us, shall not be sold or resold for
              any/commercial reasons.
            </p>
            <p className="termsP">8.3. You will not do any of the following:</p>
            <p className="termsP">
              a) Delete or modify any content on Tannis, such as any information
              regarding the services, their performance, sales or pricing;
            </p>
            <p className="termsP">
              b) Use any engine, software, tool, agent or other mechanism (such
              as spiders, robots, avatars, worms, time bombs etc.) to navigate
              or search Tannis;
            </p>
            <p className="termsP">
              c) Make false or malicious statements against the services, Tannis
              or Reliance;
            </p>
            <p className="termsP">
              d) Post, copy, submit, upload, distribute, or otherwise transmit
              or make available any software or other computer files that
              contain a virus or other harmful component, or otherwise disrupt
              or damage Tannis and/or services or any connected network, or
              otherwise interfere with any person or entity's use or enjoyment
              of Tannis and/or the Services;
            </p>
            <p className="termsP">
              e) Introduce any Trojans, viruses, any other malicious software,
              any bots or scrape Tannis for any information;
            </p>
            <p className="termsP">
              f) Probe, scan, or test the vulnerability of any system, security
              or authentication measures implemented by us or otherwise tamper
              or attempt to tamper with our technological design and
              architecture;
            </p>
            <p className="termsP">
              g) Hack into or introduce malicious software of any kind onto
              Tannis;
            </p>
            <p className="termsP">
              h) Gain unauthorised access to, or interfere with, or damage, or
              disrupt the server on which the details connected to the Services
              are stored, or any other server, computer, or database connected
              to the Services; or
            </p>
            <p className="termsP">
              i) Engage in any form of antisocial, disruptive, or destructive
              acts, including “flaming,” “spamming,” “flooding,” “trolling,”,
              “phishing” and “grieving” as those terms are commonly understood
              and used on the internet.
            </p>
            <p className="termsP">
              8.4. You are prohibited from hosting, displaying, uploading,
              modifying, publishing, transmitting, updating or sharing on or
              through Tannis, any information that:
            </p>
            <p className="termsP">
              a) belongs to another person and to which you do not have any
              right;
            </p>
            <p className="termsP">
              b) is harmful, harassing, blasphemous, defamatory, obscene,
              pornographic, paedophilic, invasive of another’s privacy, hateful,
              relating to or encouraging money laundering or gambling, or
              otherwise harmful in any manner whatsoever;
            </p>
            <p className="termsP">c) harms minors in any way;</p>
            <p className="termsP">
              d) infringes any patent, trademark, copyright or other proprietary
              rights;
            </p>
            <p className="termsP">
              e) violates any law for the time being in force;
            </p>
            <p className="termsP">
              f) deceives or misleads the addressee about the origin of such
              messages or communicates any information which is grossly
              offensive or menacing in nature;
            </p>
            <p className="termsP">
              g) impersonates or defames another person;{" "}
            </p>
            <p className="termsP">
              h) contains software viruses or any other computer code, files or
              programs designed to interrupt, destroy or limit the functionality
              of any computer resource; or
            </p>
            <p className="termsP">
              i) directly or indirectly, offers, attempts to offer, trades or
              attempts to trade in any item, dealing of which is prohibited or
              restricted in any manner under the provisions of any applicable
              law, rule, regulation or guideline for the time being in force.
            </p>
            <h2 className="termsh1">
              9. Indemnification and Limitation of Liability{" "}
            </h2>
            <p className="termsP">
              9.1. You agree to indemnify, defend and hold harmless Reliance,
              its affiliates, officers, directors, employees, consultants,
              licensors, agents, and representatives from and against any and
              all third-party claims, losses, liabilities, damages, and/or costs
              (including reasonable attorney fees and costs) arising from your
              access to or use of Tannis or the Services, violation of these
              Terms and Conditions, or infringement of any intellectual property
              or other rights of Reliance or any third-party. Reliance will
              notify you promptly of any such claim, loss, liability, or demand,
              and in addition to the foregoing, you agree to provide Reliance
              with reasonable assistance, at your expense, in defending any such
              claim, loss, liability, damage, or cost.
            </p>
            <p className="termsP">
              9.2. To the fullest extent permitted by law, in no event shall
              Reliance or any of its directors, officers, employees, agents or
              content or service providers (collectively, the “Reliance
              Representatives”) be liable to you for any direct, indirect,
              special, incidental, consequential, exemplary, special, remote or
              punitive damage, including, but not limited to damages for loss of
              profits, goodwill, use, data or other intangible losses arising
              from, or directly or indirectly related to, the use of, or the
              inability to use, Tannis or the content, materials and functions
              related thereto, the services, provision of information via
              Tannis, lost business, even if such Reliance Representatives have
              been advised of the possibility of such damages.
              <p className="termsP"></p>9.3. In no event shall Reliance
              Representatives be liable for:
            </p>
            <p className="termsP">
              a) the use or inability to use or access Tannis;
            </p>
            <p className="termsP">
              b) any content posted, transmitted, exchanged or received by or on
              behalf of any user or other person on or through Tannis;
            </p>
            <p className="termsP">
              c) any unauthorised access to or alteration of your transmissions
              of sensitive personal information or other user data; or
            </p>
            <p className="termsP">d) any other matter relating to Tannis.</p>
            <p className="termsP">
              9.4. Reliance is neither liable nor responsible for any actions or
              inactions of the other users of Tannis or any breach of
              conditions, representations or warranties by them. Reliance is not
              obligated to mediate or resolve any dispute or disagreement
              amongst two or more users of Tannis.
            </p>
            <p className="termsP">
              9.5. None of the directors, officials or employees of Reliance
              shall be personally liable for any action in connection with
              Tannis or the Services.
            </p>
            <p className="termsh1"></p>Part B -Terms of Sale on Tannis
            <p className="termsh1"></p>1. Our Contract of Sale
            <p className="termsP">
              1.1. Listing and display of a Product by us on Tannis is our
              invitation to you to make an offer for purchase of such Product.
              Likewise, the placement of an order on Tannis by you is your offer
              to buy the Product(s) from us.
            </p>
            <p className="termsP">
              1.2. Once you have placed an order with us for purchase of a
              Product, you will receive an e-mail and/or SMS confirming receipt
              of your order and containing the details of your order (the “Order
              Confirmation”). The Order Confirmation is merely an
              acknowledgement that we have received your order and does not
              signify our acceptance of your offer.
            </p>
            <p className="termsP">
              1.3. We only accept your offer and conclude the contract of sale
              for a Product ordered by you, when the Product is shipped or
              dispatched to you and an e-mail and/or SMS confirmation is sent to
              you that the Product has been shipped or dispatched to you (the
              “Shipment Confirmation”). We reserve the right, at our sole
              discretion, to refuse or cancel any order for any reason
              whatsoever before sending Shipment Confirmation to you.
            </p>
            <p className="termsP">
              1.4. If your order is dispatched in more than one package, you may
              receive separate Shipment Confirmations for each package, and each
              Shipment Confirmation and corresponding dispatch will conclude a
              separate contract of sale between you and us for the Product(s)
              specified in that Shipment Confirmation.
            </p>
            <p className="termsP">
              1.5. Your contract is with us and you confirm that the Product(s)
              ordered by you are purchased for your internal /personal purpose
              and not for re-sale or business purpose. Please note that we sell
              Products only in quantities which correspond to the usual
              requirements of an average household. This applies both to the
              number of Products ordered within a single order and the placing
              of several orders for the same Product where the individual orders
              comprise a quantity typical for a normal household.
            </p>
            <p className="termsP">
              1.6. You can cancel your order for a Product at no cost at any
              time before we send the Shipment Confirmation relating to that
              Product.
            </p>
            <p className="termsP">
              1.7. All orders placed on Tannis are subject to the availability
              of such Product, our acceptance of your offer as per the above
              terms and your continued adherence to these Terms of Sale.
            </p>
            <h2 className="termsh1"> 2. Return and refund </h2>
            <p className="termsP">
              2.1. Please review the Cancellation, Returns and Refund Policy of
              Tannis, which applies to Products sold by us.
            </p>
            <h2 className="termsh1">3. Product availability </h2>
            <p className="termsP">
              3.1. We list availability information for the Products on the
              Product display page. Beyond what we say on that Product display
              page or otherwise on Tannis, we cannot be more specific about
              availability. Please note that dispatch estimates are not
              indicative in nature and we do not guarantee the dispatch times.
              As we process your order, you will be informed by e-mail and/or
              SMS if any Products you ordered turn out to be unavailable or out
              of stock.
            </p>
            <h2 className="termsh1"> 4. Product pricing </h2>
            <p className="termsP">
              4.1. All prices are listed in Indian Rupees. Price, as displayed,
              is inclusive of all applicable taxes.
            </p>
            <p className="termsP">
              4.2. Products in your shopping cart of Tannis will reflect the
              most recent price as displayed on the Product’s information
              webpage on the website. Please note that this price may differ
              from the price shown for the Product when you first placed it in
              your shopping cart. Placing a Product in your shopping cart does
              not reserve the price shown at that time. It is also possible that
              a Product’s price may decrease between the time you place it in
              your shopping cart and the time you place the order.{" "}
            </p>
            <h2 className="termsh1">5. Sample Products </h2>
            <p className="termsP">
              5.1. We may, from time to time, offer you sample Products
              (“Samples”), free of cost, on purchases made by you on Tannis.
              Reliance reserves the sole right to decide the eligibility
              criteria for providing such Samples to you. Please note Samples
              (like Products purchased by you on Tannis), are intended for
              personal use and not for resale or further distribution. We
              reserve the right, at any point of time, with or without notice,
              to cancel or reduce the quantity of any Samples, as determined by
              us in our sole discretion.
            </p>
            <p className="termsP">
              5.2. Despite our best efforts there may be instances where, (i)
              you do not receive the Samples with your order; or (ii) the
              Samples you receive are different from the Samples you chose
              during your order; or (iii) Samples are defective or deficient. In
              such instances we will be unable to entertain any replacement or
              return request from you for the relevant Samples.{" "}
            </p>
            <p className="termsP">
              5.3. The Samples are provided on an “as is” and “as available”
              basis without any representations or warranties, express or
              implied, whatsoever. You acknowledge that consumption or use of
              Samples will be at your sole risk. The Samples may cause side
              effects or may not suit you. You agree that we will not be
              responsible for any Product defect, deficiency or side-effects in
              the Samples and you will not claim any recourse regarding your
              consumption or use of Samples provided on Tannis. We advise you to
              carefully read the Product details provided on the Samples and
              consult a specialist before the use of the Samples.
            </p>
            <h2 className="termsh1">6. Licenses </h2>
            <p className="termsP">
              6.1. You acknowledge that there may be licenses/permissions
              required under the applicable laws to use, purchase or otherwise
              possess certain Product(s). You will be solely responsible for
              obtaining such licenses/permissions and complying with the terms
              of such licenses/permissions.
            </p>
            <h2 className="termsh1">7. Taxes </h2>
            <p className="termsP"></p>7.1. You shall be responsible for payment
            of all fees/costs/charges associated with the purchase of Products
            from us and you agree to bear any and all applicable taxes. 8.
            Limitation of liability
            <p className="termsP">
              8.1. In no event, our aggregate liability, if any, that is proven
              and ordered by a court of competent jurisdiction pursuant to a
              claim by you or person acting on your behalf, shall extend beyond
              the refund of money charged from you for purchases made pursuant
              to an order under which such liability has arisen and been
              established. We will not be responsible for any business loss
              (including loss of profits, revenue, contracts, anticipated
              savings, data, goodwill or wasted expenditure) or any other
              indirect or consequential loss that is not reasonably foreseeable
              to both you and us when a contract for the sale of Product by us
              to you was formed.
            </p>
            <h2 className="termsh1">
              Part C - Miscellaneous 1. Access outside the republic of India{" "}
            </h2>
            <p className="termsP">
              1.1 Reliance makes no representation that the content on Tannis is
              appropriate to be used or accessed outside the Republic of India.
              Any users who use or access Tannis from outside the Republic of
              India, do so at their own risk and are responsible for compliance
              with the laws of such jurisdiction. These Terms do not constitute,
              nor may these Terms be used for, or in connection with, any
              promotional activities or solicitation by anyone in any
              jurisdiction in which such promotional activities or solicitation
              are not authorised or to any person to whom it is unlawful to
              promote or solicit.
            </p>
            <h2 className="termsh1">2 Term and termination </h2>
            <p className="termsP">
              2.1 These Terms shall be effective from the date of their
              publication on Tannis.
            </p>
            <p className="termsP">
              2.2 Reliance reserves the right to terminate the Services in the
              event of breach of any terms contained in these Terms and
              Conditions, misrepresentation of information, any unlawful
              activity by you or if Reliance is unable to verify or authenticate
              any information submitted by you.
            </p>
            <p className="termsP">
              2.3 You may terminate these Terms at any time, provided that you
              discontinue any further use of Tannis. However, any such
              termination shall not cancel your obligation to pay for a Product
              purchased on Tannis, or any other obligation which has accrued, or
              is unfulfilled and relates to the period, prior to termination.
            </p>
            <h2 className="termsh1"> 3 Force majeure </h2>
            <p className="termsP">
              3.1 Reliance will not be held responsible for any delay or failure
              to comply with its obligations if the delay or failure arises from
              any cause which is beyond Reliance’s reasonable control.
            </p>
            <h2 className="termsh1">4 Waiver </h2>
            <p className="termsP">
              4.1 No provision in these Terms will be deemed waived, and no
              breach excused, unless such waiver or consent is in writing and
              signed by Reliance. Any consent by Reliance to, or waiver of your
              breach, whether expressed or implied, will not constitute consent
              to, waiver of, or excuse for any other different or subsequent
              breach.
            </p>
            <h2 className="termsh1">5 Severability </h2>
            <p className="termsP">
              5.1 If any provision of these Terms is held by a court of
              competent jurisdiction to be unenforceable under applicable law,
              then such provision will be excluded from these Terms and the
              remainder of these Terms will be interpreted as if such provision
              were so excluded and will be enforceable in accordance with its
              terms; provided however that, in such event, these Terms will be
              interpreted so as to give effect, to the greatest extent
              consistent with and permitted by applicable law, to the meaning
              and intention of the excluded provision as determined by such
              court of competent jurisdiction.
            </p>
            <h2 className="termsh1">6 Governing law and dispute resolution </h2>
            <p className="termsP">
              6.1 These Terms, all transactions consummated between Reliance and
              you, and the relationship between Reliance and you is governed by
              the laws of India, without reference to any conflict of laws
              principles and with an exclusive jurisdiction to the courts of
              Mumbai.
            </p>
            <h2 className="termsh1">7 Amendment </h2>
            <p className="termsP">
              7.1 These Terms and Conditions supersede all previous oral and
              written terms and conditions (if any) communicated to you by
              Reliance, for the use of Tannis, and the rights and liabilities
              with respect to any services to be provided by Reliance shall be
              limited to the scope of these Terms.
            </p>
            <p className="termsP">
              7.2 These Terms are subject to amendments and modifications and
              may be updated from time to time, without any advance notice. You
              are requested to regularly review the Terms and Conditions as
              available on the website. Your relationship with Tannis will be
              governed by the most current version of these Terms, as published
              on Tannis.
            </p>
            <h2 className="termsh1">8 Third Party Terms and Conditions </h2>
            <p className="termsP">
              8.1 In addition to these Terms, you will also ensure that you are
              in compliance with the terms and conditions of the third parties,
              such as bank offers terms and conditions, brand promotional
              offers, whose links, if any, are contained/embedded in the
              services. You agree that Reliance will not be liable for any
              transaction between your and any such third parties.
            </p>
            <h2 className="termsh1">
              9 Consultation with Medical Practitioners{" "}
            </h2>
            <p className="termsP">
              9.1 We may provide information related to medical practitioners
              (including dermatologists) on Tannis. Any information related to
              medical practitioners made available on Tannis is strictly for
              your reference. Please note such medical practitioners are acting
              in their independent capacity and are not appointed or employed by
              Tannis. We hereby further clarify that any information related to
              such medical practitioners made available on Tannis should not be
              deemed, in any way, as endorsement by us of such medical
              practitioners.
            </p>
            <p className="termsP">
              9.2 We are merely providing information as received from the
              medical practitioners for your reference on Tannis. We have not
              independently verified the accuracy of the information received
              from the medical practitioners. We make no representation related
              to the veracity of their qualifications and/or their ability to
              provide medical advice.
            </p>
            <p className="termsP">
              9.3 You can reach out to such medical practitioners independently
              or you can use the call facility available on the Tannis app. If
              you choose to use the Tannis app call facility, Reliance will not,
              in any way, be privy to and/or record such interactions between
              the medical practitioner and you. If you choose to use the call
              facility on the Tannis app you undertake and accept that such call
              facility should only be used to book an appointment. The call
              facility should not, in any circumstance, be used to consult with
              or seek medical advice from the medical practitioners. You
              understand that you will be solely liable if you use the Tannis
              app call facility in breach of these Terms
            </p>
            <p className="termsP">
              9.4 You further agree that if you opt to seek medical guidance
              from the medical practitioners, you will do so independently and
              at your sole discretion and risk. You also unequivocally agree
              that any medical advice provided by such medical practitioner will
              be the independent opinion of the relevant medical practitioner.
              If you have any concern, dispute, complaints related to your
              interactions with the medical practitioner and/or medical advice
              received from the medical practitioner, you will be responsible
              for addressing/resolving such concerns, complaints or disputes
              directly with the relevant medical practitioner.
            </p>
            <p className="termsP">
              9.5 You represent and warrant that Reliance is in no way
              associated with and/or responsible for the interactions between
              you and the relevant medical practitioner. Therefore, under no
              circumstances will you raise any complaints, concerns or claims
              against Reliance in relation you your interactions with the
              relevant medical practitioner.
            </p>
            10 Policy Governing Product Reviews on the Platform
            <p className="termsP">
              10.1 We will encourage you to restrict any reviews/testimonials
              that you choose to publish on Tannis to be limited to the Products
              that you purchase on the platform and any input, observation or
              feedback that you may have with regards to the quality of the
              Product and/or your experience of using the Product. Your input
              and feedback with regards to a Product and its quality may act as
              valuable source of information for other users and assist them in
              their purchase decisions.
            </p>
            <p className="termsP">
              10.2 We will, however, request that you do not publish reviews
              about topics extraneous to the Product and its quality. For
              example, a review that contains the following content must be
              avoided:{" "}
            </p>
            <p className="termsP">
              a. Content that is false, inaccurate, misleading, defamatory,
              libellous, obscene, pornographic, indecent, lewd, suggestive,
              harassing, threatening, abusive, fraudulent or otherwise
              objectionable;
            </p>
            <p className="termsP">
              b) Content that infringes any third party’s copyright, patent,
              trademark, trade secret or other proprietary rights or rights of
              publicity or privacy;
            </p>
            <p className="termsP"></p>c) Content for which you were compensated
            or granted any consideration by any third party;
            <p className="termsP">
              d) Content that references other companies or website or content
              created for advertising or other commercial purposes, such as
              inclusion of a company logo, link, and company name;
            </p>
            <p className="termsP">
              e) Content that violates any local, national or international law;
            </p>
            <p className="termsP">
              f) Content that includes unsolicited promotions, mass mailings or
              spamming, political campaigning, advertising or solicitations;
            </p>
            <p className="termsP">
              g) Content that attempts to impersonate other people, accounts, or
              entities, including impersonating Tannis representatives;
            </p>
            <p className="termsP">
              h) Content that is related to your experience with respect to the
              use of Tannis and/or the Services availed on Tannis and do not
              contain content relevant to the Product or its quality;
            </p>
            <p className="termsP">
              i) Content that includes your personal information or the personal
              information of any third party.
            </p>
            <p className="termsP">
              10.3. If we encounter reviews with the abovementioned content on
              the Product page of a particular Product, we reserve the right to
              delete/remove such reviews at our sole discretion and without any
              intimation to you.{" "}
            </p>
            <p className="termsP">
              10.4. If you have any feedback and/or input regarding your access
              and use of Tannis and/or the Services provided on Tannis we will
              request you to provide such feedback/input to our customer support
              team whose contact details you can find in the next paragraph.{" "}
            </p>
            <h2 className="termsh1">11. Customer Support </h2>
            <p className="termsP">
              11.1. For any customer support for the Products available on
              Tannis or Services in connection with Tannis, you may reach write
              to us on help@tannisbeauty.com or reach out to us on the toll free
              number 1-800 890 3030 between (All days 8 AM and 8 PM).
            </p>
            <p className="termsh1">12. Grievance and Redressal</p>
            <p className="termsP">
              12.1. Should your query remain unresolved for seven (7) days or
              more after reaching out to the Customer Care, you may submit any
              grievance with respect to Tannis. You may also reach out to the
              Grievance Officer with respect to any abuse on Tannis (including
              any discrepancies or grievances with respect to access or usage of
              Tannis in violation of these Terms by any person) at:
            </p>
            <p className="termsh1"> Name: Pradeep Shinde </p>
            <p className="termsh1">Designation: Grievance Officer</p>
            <p className="termsh1">
              {" "}
              E-mail ID: grievanceofficer@tannisbeauty.com
            </p>
            <h2 className="termsh1">13. Nodal Officer</h2>
            <p className="termsh1"> Name: Heena V Chhapru </p>
            <p className="termsh1">Designation: Nodal Officer</p>
            <p className="termsh1"> E-mail ID: nodalofficer@tannisbeauty.com</p>
          </div>
        </div>
      </div>
    </Layout>
  );
}

export default TermsAndConditions;
